### ISSUE TITLE
`Error: found no frames in file {}` 

### ISSUE THREAD

**Issue by PetervanLunteren** [agentmorris/MegaDetector#154]
Currently, video_utils.py errors when it can't find frames. This results in the whole (EcoAssist) process being stopped. Would it be possible to make this a warning instead of an error? 

```
Traceback (most recent call last):
  File "C:\Users\<username>\EcoAssist_files\cameratraps\megadetector\detection\process_video.py", line 1231, in <module>
    main()
  File "C:\Users\<username>\EcoAssist_files\cameratraps\megadetector\detection\process_video.py", line 1222, in main
    process_video_folder(options)
  File "C:\Users\<username>\EcoAssist_files\cameratraps\megadetector\detection\process_video.py", line 663, in process_video_folder
    video_folder_to_frames(input_folder=options.input_video_file,
  File "C:\Users\<username>\EcoAssist_files\cameratraps\megadetector\detection\video_utils.py", line 764, in video_folder_to_frames
    _video_to_frames_for_folder(input_fn_relative,input_folder,output_folder_base,
  File "C:\Users\<username>\EcoAssist_files\cameratraps\megadetector\detection\video_utils.py", line 678, in _video_to_frames_for_folder
    frame_filenames,fs = video_to_frames(input_fn_absolute,
  File "C:\Users\<username>\EcoAssist_files\cameratraps\megadetector\detection\video_utils.py", line 647, in video_to_frames
    raise Exception('Error: found no frames in file {}'.format(input_video_file))
Exception: Error: found no frames in file <...>
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001658962e9c0] moov atom not found
```

**Comment by agentmorris** [comment]
I'm 99.7% sure that you just want to add:

--allow_empty_videos

...to your call to process_video.py.  I'm sufficiently confident that I'm going to close this issue, but LMK if that's not the behavior you want and we can re-open and find the right behavior.

**Comment by agentmorris** [comment]
Note that the reason this an error by default is that the vast majority of the time, this is legitimately an error, i.e. it's not really a video file with no frames, rather it's a missing local codec (like in the example you showed).

**Comment by PetervanLunteren** [comment]
That must have been the quickest issue fix I've ever seen ;) Thanks! I'll run it by the user to make sure it works, but if you're 99,7% sure - I'm convinced. 

https://github.com/PetervanLunteren/EcoAssist/commit/a5b28d3621bf8cf655beb5e7fccc35e5af8b32c9
